//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjdemeSi.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<bool> Gender { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
