//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjdemeSi.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public int Id { get; set; }
        public int UsersGroupId { get; set; }
        public string SenderId { get; set; }
        public string Message { get; set; }
        public bool IsEdited { get; set; }
        public bool IsRemoved { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string SeenBy { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual UsersGroup UsersGroup { get; set; }
    }
}
