//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjdemeSi.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ride
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ride()
        {
            this.Ride1 = new HashSet<Ride>();
            this.RidePassangers = new HashSet<RidePassanger>();
            this.UsersGroups = new HashSet<UsersGroup>();
        }
    
        public int Id { get; set; }
        public string DriverUserId { get; set; }
        public string FromCounty { get; set; }
        public string FromCity { get; set; }
        public string ToCounty { get; set; }
        public string ToCity { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int TravelTime { get; set; }
        public Nullable<int> DelayedStartTime { get; set; }
        public Nullable<int> BreakTime { get; set; }
        public int MaxPassengers { get; set; }
        public float TotalPrice { get; set; }
        public float PricePerPassenger { get; set; }
        public Nullable<int> ReturnRideId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string AdditionalInfo { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ride> Ride1 { get; set; }
        public virtual Ride Ride2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RidePassanger> RidePassangers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersGroup> UsersGroups { get; set; }
    }
}
