//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjdemeSi.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteLabel
    {
        public int Id { get; set; }
        public string LanguageName { get; set; }
        public string RideLocationFrom { get; set; }
        public string RideLocationTo { get; set; }
        public string RideStartDate { get; set; }
        public string RideStartTime { get; set; }
        public string RideTravelTIme { get; set; }
        public string RidePricePerPerson { get; set; }
        public string RidePricePerRide { get; set; }
        public string RideDelay { get; set; }
        public string RideBreakTime { get; set; }
        public string RidePassengers { get; set; }
    }
}
