//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjdemeSi.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrivingPassanger
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int DrivingId { get; set; }
        public Nullable<int> Rate { get; set; }
        public string RateComment { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Driving Driving { get; set; }
    }
}
