//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjdemeSi.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driving
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Driving()
        {
            this.Driving1 = new HashSet<Driving>();
            this.DrivingPassangers = new HashSet<DrivingPassanger>();
        }
    
        public int Id { get; set; }
        public string DriverUserId { get; set; }
        public string FromCounty { get; set; }
        public string FromCity { get; set; }
        public string FromPlace { get; set; }
        public string ToCounty { get; set; }
        public string ToCity { get; set; }
        public string ToPlace { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int TravelTime { get; set; }
        public int MaxPassengers { get; set; }
        public float TotalPrice { get; set; }
        public float MinTotalPrice { get; set; }
        public float PricePerPassenger { get; set; }
        public Nullable<int> ReturnDrivingId { get; set; }
        public int UsersGroupId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Driving> Driving1 { get; set; }
        public virtual Driving Driving2 { get; set; }
        public virtual UsersGroup UsersGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrivingPassanger> DrivingPassangers { get; set; }
    }
}
