CREATE TABLE [dbo].[Driving]
(
	[Id]					[int] IDENTITY(1,1) NOT NULL,
	[DriverUserId]			[nvarchar](128) NOT NULL,
	[FromCounty]			[nvarchar](128) NULL,
	[FromCity]				[nvarchar](128) NULL,
	[FromPlace]				[nvarchar](128) NULL,
	[ToCounty]				[nvarchar](128) NULL,
	[ToCity]				[nvarchar](128) NULL,
	[ToPlace]				[nvarchar](128) NULL,
	[StartTime]				[datetime]		NOT NULL,
	[EndTime]				[dateTime]		NOT NULL,
	[TravelTime]			[int]			NOT NULL,
	[MaxPassengers]			[int]			NOT NULL,
	[TotalPrice]			[real]			NOT NULL,
	[MinTotalPrice]			[real]			NOT NULL,
	[PricePerPassenger]		[real]			NOT NULL,
	[ReturnDrivingId]		[int]			NULL,
	[UsersGroupId]			[int]			NOT NULL,
	[DateCreated]			DATETIME NULL		DEFAULT(getdate()),
	
	CONSTRAINT [PK_dbo.Driving] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_dbo.Driving_dbo.AspNetUsers_UserId] FOREIGN KEY([DriverUserId]) REFERENCES [dbo].[AspNetUsers] ([Id]),
	CONSTRAINT [FK_dbo.Driving_dbo.Driving_Id] FOREIGN KEY([ReturnDrivingId]) REFERENCES [dbo].[Driving] ([Id]),
	CONSTRAINT [FK_dbo.Driving_dbo.UsersGroup_UsersGroupId] FOREIGN KEY([UsersGroupId]) REFERENCES [dbo].[UsersGroup] ([Id]),
)
